icons_format = "{icon}"


[icons]
icons = "awesome6"
[icons.overrides]


[theme]
theme = "ctp-macchiato"
[theme.overrides]
# idle_bg = "#2B4162"
idle_fg = "#abcdef"

[[block]]
block = "custom"
command = "echo \uf26c" 
interval = "once"
[[block.click]]
button = "left"
cmd = "xrandr --output eDP --off --output HDMI-A-0 --primary --mode 1920x1080 --pos 0x0 --rotate normal"

[[block]]
block = "custom"
command = "echo \uf08e" 
interval = "once"
[[block.click]]
button = "left"
cmd = "xrandr --output eDP --mode 1920x1080 --pos 0x1080 --rotate normal --output HDMI-A-0 --mode 1920x1080 --pos 0x0 --rotate normal"

[[block]]
block = "focused_window"
[block.format]
full = " $title.str(max_w:15) |"
short = " $title.str(max_w:10) |"

[[block]]
block = "tea_timer"
format = " \uf7b6  {$minutes:$seconds |}"
done_cmd = "notify-send 'Timer Finished'"

[block.theme_overrides]
# idle_bg = "#2B4162"
idle_fg = "#f7accf"
[block.icons_overrides]

[[block]]
block = "bluetooth"
mac = "98:A5:F9:54:92:55"
disconnected_format = ""
format = " $icon $name"
[block.battery_state]
"0..20" = "critical"
"21..70" = "warning"
"71..100" = "good"

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:20,rot_interval:0.5) $prev $play $next |}"
player = "spotify"

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid $frequency|Wired connection} via $device "
[block.theme_overrides]
# idle_bg = "#2B4162"
idle_fg = "#04e824"
[block.icons_overrides]

[[block]]
block = "speedtest"
interval = 120
format = "\uf063 $speed_down.eng(w:4,u:B) \uf062 $speed_up"

[[block]]
block = "sound"
[[block.click]]
button = "left"
[block.theme_overrides]
# idle_bg = "#2B4162"
idle_fg = "#8651c9"
[block.icons_overrides]
cmd = "pavucontrol"


[[block]]
# [block.theme_overrides]
# idle_bg = "#2B4162"
# idle_fg = "#8651c9"
# [block.icons_overrides]
block = "battery"
format = " $icon $percentage "
charging_format=" \uf0e7 $percentage "

[[block]]
block = "load"
format = " $icon 1min avg: $1m.eng(w:4) "
interval = 1

[[block]]
block = "cpu"
icons_format = "{icon} CPU"
[block.theme_overrides]
idle_bg = "#2B4162"
idle_fg = "#8651c9"
[block.icons_overrides]
cpu_boost_on = "ON"
cpu_boost_off = "OFF"


[[block]]
block = "memory"
format = " $icon MEMORY $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "
[block.theme_overrides]
 idle_bg = "#2B4162"
idle_fg = "#04E824"
[block.icons_overrides]


[[block]]
block = "disk_space"
path = "~/projects"
info_type = "used"
alert_unit = "MB"
interval = 10
format = " \uf802 $used.eng(w:2) "

[[block]]
block = "disk_space"
path = "/home"
info_type = "available"
alert_unit = "GB"
interval = 10
warning = 20.0
alert = 10.0
format = " \ue1b0 /home $available.eng(w:2) "

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 10
warning = 20.0
alert = 10.0
format = " $icon /-_- $available.eng(w:2) "


[[block]]
block = "uptime"
interval = 3600
format = " $icon UPTIME $text "
[block.theme_overrides]
# idle_bg = "#2B4162"
idle_fg = "#f4d35e"
[block.icons_overrides]

[[block]]
block = "time"
interval = 5
format = "$icon $timestamp.datetime(f:'%a %d/%m %r') "
[block.theme_overrides]
# idle_bg = "#2B4162"
idle_fg = "#e3d985"
[block.icons_overrides]

